### ISSUE TITLE
【显示被引用的回复】功能相关问题

### ISSUE THREAD

**Issue by Future23365** [v2hot/v2ex.rep#3]
这个功能很好用！但是当【被引用】的回复在当前回复的上一楼时，此时是不会内嵌显示被引用的回复的。这样感觉很割裂，可不可以保持一致呢，始终显示被引用的回复。

**Comment by PipecraftNet** [comment]
> 但是当【被引用】的回复在当前回复的上一楼时，此时是不会内嵌显示被引用的回复的。这样感觉很割裂，可不可以保持一致呢，始终显示被引用的回复。

因为上一楼的内容可以直接看到，下面再显示相同的内容的话，觉得有些多余。
下个版本加一个设置，让用户选择是否始终显示吧。

**Comment by PipecraftNet** [comment]
> > 但是当【被引用】的回复在当前回复的上一楼时，此时是不会内嵌显示被引用的回复的。这样感觉很割裂，可不可以保持一致呢，始终显示被引用的回复。
> 
> 因为上一楼的内容可以直接看到，下面再显示相同的内容的话，觉得有些多余。 下个版本加一个设置，让用户选择是否始终显示吧。

@Future23365 
1.5.4 版本已发布，选择“始终显示”即可。

<img width="745" alt="2023-09-04-10-04-14" src="https://github.com/v2hot/v2ex.rep/assets/88728670/9c9051f9-1eb4-4991-96e4-ee4ad01d3c3c">

**Comment by Future23365** [comment]
> > > 但是当【被引用】的回复在当前回复的上一楼时，此时是不会内嵌显示被引用的回复的。这样感觉很割裂，可不可以保持一致呢，始终显示被引用的回复。
> > 
> > 
> > 因为上一楼的内容可以直接看到，下面再显示相同的内容的话，觉得有些多余。 下个版本加一个设置，让用户选择是否始终显示吧。
> 
> @Future23365 1.5.4 版本已发布，选择“始终显示”即可。
> <img alt="2023-09-04-10-04-14" width="745" src="https://user-images.githubusercontent.com/88728670/265305861-9c9051f9-1eb4-4991-96e4-ee4ad01d3c3c.png">

哇！效率真高！感谢感谢！！！❤️
